### ISSUE TITLE
Devices partially responding

### ISSUE THREAD

**Issue by abailey22** [rodtoll/isy-js#15]
I've had this same issue two days in a row where I can turn devices on but not off. When commanding Siri to turn the deviced off she responds with "ok, the device is off" but it is still on. With a simple restart of the homebridge service everything starts working again. What steps can I perform to help troubleshoot this?

**Comment by rodtoll** [comment]
Hi @abailey22. Sorry to hear you are having this trouble.

Some questions to kick off the troubleshooting:
1) Is it a specific device that has this problem or all the devices in your setup? i.e. Can others turn off when this is happening?
2) Can you set the dim level of the light? i.e. Set the Kitchen Table to 50%. i.e. Is it all commands to the impacted light or just this one? (Only try this if the light is dimmable of course).
3) Do you know if it just happens after awhile or after a certain number of off and ons?
4) Is the impacted light part of a scene? If so, is it the controller or a responder?
5) If it is just the one light then post the node information for your device so I can look at the device config. Hit http://<your isy address>/rest/nodes and look for the device in the list and post the XML for that device. For example, my kitchen table light config:

```
<node flag="128">
<address>19 51 9E 1</address>
<name>Kitchen Table</name>
<parent type="3">42035</parent>
<type>1.32.64.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>19 51 9E 1</pnode>
<ELK_ID>E10</ELK_ID>
<property id="ST" value="255" formatted="On" uom="%/on/off"/>
</node>
```
1. When it gets into the bad situation it would be good to get the node information as above at that moment. (That will tell us if the node is out of synch).

**Comment by abailey22** [comment]
It happened with a number of lights yesterday. Three are on SwitchLincs, one plugin dimmer and one is a FanLinc. I'll check out the steps you gave us our happens again.

-Austin

**Comment by abailey22** [comment]
Hey @rodtoll, I have done some testing tonight. I had the same issue after leaving HomeBridge running all day. I have included my comments in-line below.

Some questions to kick off the troubleshooting:
1) Is it a specific device that has this problem or all the devices in your
setup? i.e. Can others turn off when this is happening? - Happens to
SwitchLincs, LampLincs and FanLincs
2) Can you set the dim level of the light? i.e. Set the Kitchen Table to
50%. i.e. Is it all commands to the impacted light or just this one? (Only
try this if the light is dimmable of course). Yes, I can change the dim
level to 50%.
3) Do you know if it just happens after awhile or after a certain number of
off and ons? It seems to be after time. After restarting the HomeBridge
service I was able to turn the lights on and off and dim repeatedly without
any issue.
4) Is the impacted light part of a scene? If so, is it the controller or a
responder? - This is direct control of devices. Not a Scene.
5) If it is just the one light then post the node information for your
device so I can look at the device config. Hit http:///rest/nodes and look
for the device in the list and post the XML for that device. For example,
my kitchen table light config:

<node flag="128">
<address>19 51 9E 1</address>
<name>Kitchen Table</name>
<parent type="3">42035</parent>
<type>1.32.64.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>19 51 9E 1</pnode>
<ELK_ID>E10</ELK_ID>
<property id="ST" value="255" formatted="On" uom="%/on/off"/>
</node>
1. When it gets into the bad situation it would be good to get the node
   information as above at that moment. (That will tell us if the node is out
   of synch).  According to HomeKit (via MyTouchHome) the devices are off but
   according to ISY they are at 60%. I had my living room light on before
   testing (turned on manually). Asked Siri to turn it off and she did. I then
   asked her to turn it back on and she said it was turned on but the light is
   still off. This is the FanLinc listed below.

## LampLinc - Turn on, dimmed to 50% and won't turn off

<node flag="128">
<address>1 26 D0 1</address>
<name>Cabinet Rope Lights</name>
<parent type="3">9359</parent>
<type>1.0.36.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>1 26 D0 1</pnode>
<ELK_ID>A09</ELK_ID>
<property id="ST" value="153" formatted="60" uom="%/on/off"/>
</node>

## SwitchLincs - Turn on, dimmed to 50% and won't turn off

<node flag="128">
<address>22 51 BB 1</address>
<name>Kitchen - 2 Lights</name>
<parent type="3">9359</parent>
<type>1.32.65.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>22 51 BB 1</pnode>
<ELK_ID>A03</ELK_ID>
<property id="ST" value="128" formatted="51" uom="%/on/off"/>
</node>

<node flag="128">
<address>6 C1 B6 1</address>
<name>Kitchen - 4 Lights</name>
<parent type="3">9359</parent>
<type>1.1.39.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>6 C1 B6 1</pnode>
<ELK_ID>A02</ELK_ID>
<property id="ST" value="128" formatted="51" uom="%/on/off"/>
</node>

## FanLinc - Turn off and won't turn on

<node flag="128">
<address>14 9C BB 1</address>
<name>Living Room Light</name>
<parent type="3">57882</parent>
<type>1.46.65.137</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>14 9C BB 1</pnode>
<ELK_ID>E09</ELK_ID>
<property id="ST" value="0" formatted="Off" uom="%/on/off"/>
</node>

---

After restarting the HomeBridge service, this is the node information

## LampLinc

<node flag="128">
<address>1 26 D0 1</address>
<name>Cabinet Rope Lights</name>
<parent type="3">9359</parent>
<type>1.0.36.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>1 26 D0 1</pnode>
<ELK_ID>A09</ELK_ID>
<property id="ST" value="0" formatted="Off" uom="%/on/off"/>
</node>

## SwitchLincs - Turn on, dimmed to 50% and won't turn off

<node flag="128">
<address>22 51 BB 1</address>
<name>Kitchen - 2 Lights</name>
<parent type="3">9359</parent>
<type>1.32.65.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>22 51 BB 1</pnode>
<ELK_ID>A03</ELK_ID>
<property id="ST" value="0" formatted="Off" uom="%/on/off"/>
</node>

<node flag="128">
<address>6 C1 B6 1</address>
<name>Kitchen - 4 Lights</name>
<parent type="3">9359</parent>
<type>1.1.39.0</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>6 C1 B6 1</pnode>
<ELK_ID>A02</ELK_ID>
<property id="ST" value="0" formatted="Off" uom="%/on/off"/>
</node>

## FanLinc - Turn off and won't turn on

<node flag="128">
<address>14 9C BB 1</address>
<name>Living Room Light</name>
<parent type="3">57882</parent>
<type>1.46.65.137</type>
<enabled>true</enabled>
<deviceClass>0</deviceClass>
<wattage>0</wattage>
<dcPeriod>0</dcPeriod>
<pnode>14 9C BB 1</pnode>
<ELK_ID>E09</ELK_ID>
<property id="ST" value="242" formatted="95" uom="%/on/off"/>
</node>

**Comment by rodtoll** [comment]
@abailey22 - Apologies I dropped off there and left you hanging.

The symptom sounds like the ISY library copy of the device state and the actual device state are out of sync. The result is you are trying to change the state and the ISY library is ignoring what it thinks is a redundant command. 

The only way this can happen is if the websocket connection from the ISY, which updates the ISY library state locally is broken somehow. If it dropped outright then there would be an error and a crash. If you have something that restarts it automatically on a crash perhaps it restarted and failed to reconnect. I'll need to do some further testing to see how robust my code is for a failure at startup.

One of the main causes of failure for the websocket connection is that the ISY device is only able to support a limited number of these websocket callbacks. Over a long period of time perhaps these got used up. Rebooting your ISY should clear the problem if this is the case. Reboot it and restart homebridge. If you can then run longer then this is the root cause.

Another potential cause is certainly a bug in the code. If this is the case then I need you to enable debug logging and reproduce the issue. To do so you simply add the following entry in the config.json file, in the homebridge-isy section:

```
        "debugLoggingEnabled": true,
```

This will enable debug output to the console. However you are running homebridge hopefully captures console output. Then when it gets into the bad condition see if there is an error message in the output you can see.

If you don't see an error try changing state of the devices which won't change and capture the debug output then. With debug logging on we should see what command it is trying to send to ISY and see if there is some kind of unexpected error or inconsistent state.

One last option -- ensure you have the latest stable version of the firmware for your ISY. There have been versions of the firmware that were broken when it comes to websocket callbacks. 

And of course, if you have moved on from this issue, which would be reasonable given my delay in getting back to you, I totally understand.

**Comment by rodtoll** [comment]
@abailey22 please reactivate if this is still a problem. Apologies I didn't get back to you sooner.
