### ISSUE TITLE
Polyglot Hue support / RGB LED Support

### ISSUE THREAD

**Issue by cswelin** [rodtoll/isy-js#19]
Since the introduction of Polygot (node server), the ISY has the ability to communicate with a Hue bridge (maybe more in the future).

What are the chances of adding support for this? 

currently I can get basic support for the lights (on/off/brightness) by just adding familyID 10  `if(familyId == 1 || familyId == 10) {` but having RGB would be nice.

If there's any information or data dump required, id be willing to help

Device Node outputs:
Pastern: [http://pastebin.com/HYu7C6Yd](http://pastebin.com/HYu7C6Yd)

**Comment by rodtoll** [comment]
I hadn't added support yet for node server types because in many cases
there are native npm packages to talk to these other platforms. I felt it
was better, if you need to talk to them to use their native protocols.

For example the are a few JavaScript libraries for accessing hue. For
example https://www.npmjs.com/package/hue.js.

I'll give node types some thought as it won't be just lights. And I would
want to make sure it recognized other classes as well.

In the meantime you could try one of the other libraries.

**Comment by cswelin** [comment]
Fair enough there could be infinite types , I've been using the hue plugin mostly.

Thanks
